name: yml file
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
   # container: rzsolt/diploma-latex:latest
    steps:
      - uses: actions/checkout@v2
     # - run: echo 'Compiling LaTeX document...'
     # - run: make 
     # - run: echo 'Storing artifact...'
     # - uses: actions/upload-artifact@v1
     #   with:
     #     name: Final document
     #     path: thesis_with_cover.pdf
